### PR TITLE
Status Dashboard

### LINKED ISSUE #17: Implement dashboard interface
## 📌 Summary

Extend the deployed Quetz dashboard with the newly designed interfaces for maintainers.

## 📝 Background

This is the frontend counterpart of "Review and add needed Quetz plugins for the backend".

The needed UI elements need to be designed and implemented in the Quetz frontend, following the style guide proposed in the first milestone.

## 🚀 Tasks / Deliverables

- [x] https://github.com/conda-forge/conda-forge.github.io/pull/2090
  - Screencast:

https://github.com/Quansight-Labs/cf-infra-docs/assets/159529/2ba95b2b-378e-4168-9f5b-b088094a7802

## 📅 Estimated completion

This task should be finished in the first [12 months](https://github.com/Quansight-Labs/czi-conda-forge-mgmt/milestone/2).

### PR DESCRIPTION
**Pull request by afshin**
This is an updated status/dashboard page for the conda-forge website.

Please try it out: [this PR's deployment](https://deploy-preview-12--cf-infra-docs.netlify.app/status)

This PR covers the functionality every core component of the current conda-forge site:

- [x] Incidents
- [x] Repos and Bots
- [x] Cloud Services
- [x] Current Migrations
- [x] Migration Details
- [x] Version Updates
- [x] Azure Pipeline Usage
- [x] GitHub Actions Usage
- [x] Travis CI Usage

### <span aria-hidden="true">✅</span> Deploy Preview for *cf-infra-docs* ready!

|  Name | Link |
|:-:|------------------------|
|<span aria-hidden="true">😎</span> Deploy Preview | [https://deploy-preview-12--cf-infra-docs.netlify.app/status](https://deploy-preview-12--cf-infra-docs.netlify.app/status) |
|<span aria-hidden="true">📱</span> Preview on mobile | <details><summary> Toggle QR Code... </summary><br /><br />QR Code<br /><br />_Use your smartphone camera to open QR code link._</details> |
---

Here is screencast of this branch:

https://github.com/Quansight-Labs/cf-infra-docs/assets/159529/2ba95b2b-378e-4168-9f5b-b088094a7802

### CODE REVIEW

**Comment by jaimergp** [comment]
AFAIK, the incidents data is [served](https://github.com/conda-forge/status/blob/762e91eb2faf1a04234c1d38fa1de29810612371/render_page.py#L20-L57) from the GH issues posted at https://github.com/conda-forge/status, which get rendered to the HTML site. To avoid using the GH API on the client side, we can add one more output to the pipelines there so they render some JSON.

**Comment by jaimergp** [comment]
Also [Docusaurus 3.0](https://docusaurus.io/blog/releases/3.0) is out with some breaking changes in MDX. I don't think it will incur any work for us, but better transition sooner than later.

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
@jaimergp If you know how to resolve the CI failures or if someone on your team does, I would appreciate the help! It builds locally for me with a few warnings but no errors. I tried updating my dependencies to see if that would resolve it and I asked the pre-commit.ci task to autofix the failing `prettier` task, but the others fail in the `npm run build` phase.

This is not blocking my progress, but it *is* blocking the ability of others to see my progress without building the site on their own machines because it is no longer deploying automatically to netlify.

**Comment by jaimergp** [comment]
Thanks for the ping @afshin. Is it ok if I push to your branch with potential fixes? I didn't start looking into it yet so just in case.

**Comment by jaimergp** [comment]
Well, I cleared the netlify cache and it should work now: https://6564c75b51a6ff0da5dcc594--cf-infra-docs.netlify.app/status/

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
Thank you @jaimergp!

**Comment by jaimergp** [comment]
FYI (not urgent) we have added open-gpu-server monitoring for the GPU CI. It simply uses [this endpoint](https://conda-forge.herokuapp.com/status-monitor/open-gpu-server), with [these possible values](https://docs.openstatus.dev/getting-started/status-widget) for `status`.

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by SylvainCorlay** [comment]
This is looking great!

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by jaimergp** [comment]
This is amazing and it looks fantastic, @afshin. Now that we have PR previews in the [conda-forge.org repo too](https://github.com/conda-forge/conda-forge.github.io/pulls), could you take this branch and submit it as a PR there? We'll need to do it eventually and this way the PR will get more visibility from the community. I'll start taking a look here but will publish my review in the other repo.

**Comment by afshin** [comment]
Thanks @jaimergp! I had trouble getting the main repo to build following the instructions there and I was worried it would block progress so I continued here. I was going to ask for help on Tuesday's call.

**Comment by jaimergp** [comment]
Ok, let me take a look!

**Comment by jaimergp** [comment]
Ok, I got it, the only problem I found was in `package.json`. I had to adjust `prism-react-renderer`. Try with this one:

```json
{
  "name": "cf-infra-docs",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "docusaurus": "docusaurus",
    "start": "docusaurus start",
    "build": "docusaurus build",
    "swizzle": "docusaurus swizzle",
    "deploy": "docusaurus deploy",
    "clear": "docusaurus clear",
    "serve": "docusaurus serve",
    "write-translations": "docusaurus write-translations",
    "write-heading-ids": "docusaurus write-heading-ids",
    "prettier": "prettier --list-different --write \"**/*{.js,.jsx,.css,.json,.md,.mdx,.yaml}\""
  },
  "dependencies": {
    "@docusaurus/core": "^3.1.1",
    "@docusaurus/plugin-client-redirects": "^3.1.1",
    "@docusaurus/preset-classic": "^3.1.1",
    "@docusaurus/theme-mermaid": "^3.1.1",
    "@mdx-js/react": "^3.0.0",
    "chart.js": "^4.4.0",
    "chartjs-adapter-moment": "^1.0.1",
    "clsx": "^1.2.1",
    "install": "^0.13.0",
    "moment": "^2.29.4",
    "octokit": "^3.1.2",
    "prism-react-renderer": "^2.3.1",
    "react": "^18.2.0",
    "react-chartjs-2": "^5.2.0",
    "react-dom": "^18.2.0",
    "react-markdown": "^9.0.1",
    "remark-gfm": "^4.0.0",
    "uninstall": "^0.0.0"
  },
  "devDependencies": {
    "@docusaurus/module-type-aliases": "^3.1.1",
    "prettier": "^2.7.1"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "engines": {
    "node": ">=18.0"
  }
}
```

**Comment by jaimergp** [comment]
We'll soon merge a PR that moves all the documentation to Docusaurus, so at that point building the website is simply `npm install && npm run start`. Maybe simpler to wait til tomorrow.

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
pre-commit.ci autofix

**Comment by afshin** [comment]
Closing in favor of: https://github.com/conda-forge/conda-forge.github.io/pull/2090

**Pull request closed without merging**
